### ISSUE TITLE
About the training code.

### ISSUE THREAD

**Issue by stefenmax** [LingxiaoYang2023/DSG2024#1]
Great work! 
Will you release the training codes/sripts? Thanks

**Comment by LingxiaoYang2023** [comment]
The current code of DSG is based on DPS(https://github.com/DPS2022/diffusion-posterior-sampling), and DPS does not provide the train code. If you want to train the diffusion model, I recommend referring to the issues in DPS (e.g. https://github.com/DPS2022/diffusion-posterior-sampling/issues/3).
