### ISSUE TITLE
(Some weights were not used when initializing CLIPTextModel)

### ISSUE THREAD

**Issue by Leiii-Cao** [LingxiaoYang2023/DSG2024#10]
Thank you very much for your excellent work！！ But when I use DSG for style transfer in latent diffusion (based on Freedom), there is a mismatch in CLIP parameters. Although it does not seem to affect the operation, I would like to ask if you have the same situation. Below is my error and the pre-trained model imported into CLIP

<img width="1591" alt="image" src="https://github.com/user-attachments/assets/f3bd2f5e-12de-4b28-a775-7a080b98995d" />

<img width="521" alt="image" src="https://github.com/user-attachments/assets/1e938613-437d-49b0-8417-18165d03e7c0" />
****

**Comment by LingxiaoYang2023** [comment]
This is the standard output from the original Freedom code, and to the best of my recollection, I haven't made any modifications to it.
