### ISSUE TITLE
Something error in DSG Sample

### ISSUE THREAD

**Issue by MaoAYD** [LingxiaoYang2023/DSG2024#2]
I get an error when run the DGS_run.sh
"""
grad_norm = torch.linalg.norm(grad, dim=[1, 2, 3])
RuntimeError: linalg.norm: If dim is specified, it must be of length 1 or 2. Got [1, 2, 3]
"""

**Comment by LingxiaoYang2023** [comment]
I did not encounter this problem, but it seems that the input format may not be correct. Please check the input size which is (1,c,h,w) instead of (c,h,w).

**Comment by LingxiaoYang2023** [comment]
This issue might be associated with the version of PyTorch you are using. Please verify that you have PyTorch version 1.11.0+cu113 installed, as specified in the README. Alternatively, you may also calculate the gradient norm using _grad_norm = torch.linalg.norm(grad)_, which utilizes the default parameter of _dim_.
