### ISSUE TITLE
About d_sample

### ISSUE THREAD

**Issue by luckysyj** [LingxiaoYang2023/DSG2024#6]
Thank you for you excellent work ! But I have a question about d_sample. In the pseudo-code, the d_sample= σ * ϵ. but in code, d_sample=x_t - x_t_mean. I don't understand what x_t_mean means. Thank you for your answer !

**Comment by LingxiaoYang2023** [comment]
The term "x_t_mean" refers to the posterior mean  \mu_\theta(x_t),  where x_t represents the sample point. Therefore, x_t can be expressed x_t = x_t_mean + \sigma \epsilon. (e.g. Line 452, _guided_diffusion/gaussian_diffusion.py_).
