### ISSUE TITLE
Using SD1.4 cannot reconstruct image y when applying L(\hat{x0}, y)

### ISSUE THREAD

**Issue by Tonniia** [LingxiaoYang2023/DSG2024#9]
Hi, when I use code in SD_style with SDv1.4, and I want to reconstruct a image: 
```
def get get_residual(x0, y):
  differences = x0 - y
  return differences
```
The reconstruction is unsatisfied.
input:![image](https://github.com/user-attachments/assets/43239708-1ad5-460b-9116-d8dc18bb801f)
output:![image](https://github.com/user-attachments/assets/90a8929e-4895-42a0-811b-c975f283f70c)
Does it because the limitation of SD model (VAE limitation)?

**Comment by LingxiaoYang2023** [comment]
This could be caused by several reasons: 1. The error in the VAE as you said. 2. The data domain of Stable Diffusion is too large, leading to the need for more NFEs for optimization. 3. The generated image quality seems low; you might need to use a smaller guidance rate and a larger interval.
